### GET request to find article by id
GET http://localhost:8080/articles/5
###

### POST request to create article
POST http://localhost:8080/articles
Content-Type: application/json

{
  "title": "New Tech Trends",
  "content": "An article about new tech trends.",
  "author": {
    "id": 1
  },
  "categories": [
    {"id": 1},
    {"id": 2}
  ]
}

### POST request to create article without author associated and categories
POST http://localhost:8080/articles
Content-Type: application/json

{
  "title": "Test Article",
  "content": "Test description."
}

### POST request to create article without author associated and categories - invalid
POST http://localhost:8080/articles
Content-Type: application/json

{
  "id": 1,
  "title": "Test Article",
  "content": "Test description."
}

### DELETE article by id
DELETE http://localhost:8080/articles/11